BeamMeUp_SV =
{
    ["Default"] = 
    {
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["hideDelves"] = false,
                ["infoFavoritePlayerStatusNotification"] = false,
                ["showOpenButtonOnMap"] = true,
                ["HideOnMapClose"] = true,
                ["infoSurveyMapsNotification"] = false,
                ["closeOnPorting"] = true,
                ["windowStay"] = false,
                ["hidePVP"] = true,
                ["focusZoneSearchOnOpening"] = false,
                ["chatButton"] = true,
                ["lastPortedZones"] = 
                {
                },
                ["anchorMapOffset_x"] = 0,
                ["savedGold"] = 0,
                ["Scale"] = 1,
                ["numberLines"] = 10,
                ["totalPortCounter"] = 0,
                ["pos_y"] = 63,
                ["portCounterPerZone"] = 
                {
                },
                ["HintOfflineWhisper"] = true,
                ["initialTimeStamp"] = 1731926812,
                ["autoRefreshFreq"] = 5,
                ["unlockingLessChatOutput"] = false,
                ["currentViewedZoneAlwaysTop"] = false,
                ["onlyMaps"] = false,
                ["hidePublicDungeons"] = false,
                ["showNumberPlayers"] = true,
                ["pos_x"] = -15,
                ["anchorOnMap"] = true,
                ["fixedWindow"] = false,
                ["surveyMapsNotification"] = false,
                ["useMapPing"] = false,
                ["showTeleportAnimation"] = true,
                ["formatZoneName"] = false,
                ["currentZoneAlwaysTop"] = false,
                ["autoRefresh"] = true,
                ["showZonesWithoutPlayers2"] = true,
                ["pos_MapScene_y"] = 63,
                ["hideHouses"] = false,
                ["anchorMapOffset_y"] = 0,
                ["hideOthers"] = true,
                ["hideClosedDungeons"] = true,
                ["pos_MapScene_x"] = -15,
                ["AutoPortFreq"] = 300,
                ["surveyMapsNotificationSound"] = true,
                ["searchCharacterNames"] = false,
                ["hideOwnHouses"] = false,
                ["usePanAndZoom"] = true,
                ["zoneOnceOnly"] = true,
                ["chatButtonHorizontalOffset"] = 0,
                ["ShowOnMapOpen"] = true,
                ["secondLanguage"] = 1,
                ["autoUnlockChatLogging"] = true,
                ["version"] = 2,
                ["wayshrineTravelAutoConfirm"] = false,
                ["showOfflineReminder"] = true,
                ["FavoritePlayerStatusNotification"] = true,
                ["infoBMUGuild"] = true,
            },
            ["8796093077413993"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Jonzouio",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
            },
        },
        ["@Kankerkop"] = 
        {
            ["8796093078606003"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Kankerkop",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
            },
            ["$AccountWide"] = 
            {
                ["hideDelves"] = false,
                ["chatOutputFastTravel"] = true,
                ["infoFavoritePlayerStatusNotification"] = false,
                ["showOpenButtonOnMap"] = true,
                ["HideOnMapClose"] = true,
                ["infoSurveyMapsNotification"] = false,
                ["closeOnPorting"] = true,
                ["windowStay"] = false,
                ["hidePVP"] = true,
                ["focusZoneSearchOnOpening"] = false,
                ["chatButton"] = true,
                ["lastPortedZones"] = 
                {
                    [1] = 104,
                    [2] = 104,
                    [3] = 104,
                    [4] = 1086,
                    [5] = 1086,
                    [6] = 57,
                    [7] = 3,
                    [8] = 57,
                    [9] = 383,
                    [10] = 57,
                    [11] = 1027,
                    [12] = 57,
                    [13] = 849,
                    [14] = 1196,
                    [15] = 383,
                    [16] = 19,
                    [17] = 849,
                    [18] = 57,
                    [19] = 41,
                    [20] = 57,
                },
                ["pos_MapScene_y"] = 139,
                ["savedGold"] = 16952,
                ["Scale"] = 1,
                ["FavoritePlayerStatusNotification"] = true,
                ["pos_x"] = -15,
                ["hidePublicDungeons"] = false,
                ["useMapPing"] = false,
                ["portCounterPerZone"] = 
                {
                    [849] = 2,
                    [19] = 1,
                    [1027] = 1,
                    [1286] = 1,
                    [103] = 1,
                    [104] = 4,
                    [41] = 2,
                    [3] = 1,
                    [57] = 9,
                    [1196] = 1,
                    [381] = 1,
                    [1086] = 2,
                    [383] = 3,
                },
                ["HintOfflineWhisper"] = true,
                ["chatOutputUnlock"] = true,
                ["autoRefreshFreq"] = 5,
                ["fixedWindow"] = false,
                ["chatButtonHorizontalOffset"] = 0,
                ["pos_y"] = 63,
                ["onlyMaps"] = false,
                ["showNumberPlayers"] = true,
                ["currentViewedZoneAlwaysTop"] = false,
                ["anchorOnMap"] = false,
                ["secondLanguage"] = 1,
                ["surveyMapsNotification"] = false,
                ["chatOutputAdditional"] = true,
                ["showTeleportAnimation"] = true,
                ["currentZoneAlwaysTop"] = false,
                ["formatZoneName"] = false,
                ["autoRefresh"] = true,
                ["showZonesWithoutPlayers2"] = true,
                ["zoneOnceOnly"] = true,
                ["hideHouses"] = false,
                ["anchorMapOffset_y"] = 0,
                ["hideOthers"] = true,
                ["hideClosedDungeons"] = true,
                ["pos_MapScene_x"] = 133,
                ["anchorMapOffset_x"] = 0,
                ["surveyMapsNotificationSound"] = true,
                ["searchCharacterNames"] = false,
                ["initialTimeStamp"] = 1746342521,
                ["AutoPortFreq"] = 300,
                ["hideOwnHouses"] = false,
                ["usePanAndZoom"] = true,
                ["ShowOnMapOpen"] = true,
                ["numberLines"] = 16,
                ["totalPortCounter"] = 29,
                ["version"] = 2,
                ["wayshrineTravelAutoConfirm"] = false,
                ["showOfflineReminder"] = true,
                ["showContextMenuIcons"] = true,
                ["infoBMUGuild"] = true,
            },
            ["8796093079748457"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Kaaskop",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
        },
        ["@noobkiss"] = 
        {
            ["8796093077622069"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobwick",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077546265"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Galen Chef Mike",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093080474427"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Vex Vex Loop",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077286759"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Lumina Hoaying",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093078078769"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobmiss",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077575525"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Joyous Socks",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093080564143"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Wasted Wasted",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077280469"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobxoxo",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077280363"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobsmile",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077338611"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobsimper",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8798292100191884"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobkiss",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077286887"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobhappy",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093080650625"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Flawed Mangoes",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077142221"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobxoxo",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
            },
            ["8796093080475359"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Hymn Hemy",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093076445407"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobkiss",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077976825"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Sunken Feb",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093078739949"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobbomb",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077354797"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobsmell",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = true,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093079602369"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Zou Kimcheng",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093080474203"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Dizzy Dizzo",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077575729"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobwick",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
            },
            ["8796093080564087"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Wasted Wasted",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077977575"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Killswitch Memories",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077130605"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobhugs",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077546157"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobsmirk",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
            },
            ["8796093078411849"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Young Ming",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077280431"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "noobwink",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["$AccountWide"] = 
            {
                ["hideDelves"] = false,
                ["chatOutputFastTravel"] = true,
                ["infoFavoritePlayerStatusNotification"] = false,
                ["showOpenButtonOnMap"] = true,
                ["HideOnMapClose"] = true,
                ["infoSurveyMapsNotification"] = false,
                ["formatZoneName"] = false,
                ["windowStay"] = false,
                ["hidePVP"] = true,
                ["focusZoneSearchOnOpening"] = false,
                ["chatButton"] = true,
                ["lastPortedZones"] = 
                {
                    [1] = 104,
                    [2] = 104,
                    [3] = 849,
                    [4] = 1318,
                    [5] = 3,
                    [6] = 19,
                    [7] = 19,
                    [8] = 101,
                    [9] = 57,
                    [10] = 92,
                    [11] = 92,
                    [12] = 117,
                    [13] = 104,
                    [14] = 383,
                    [15] = 1318,
                    [16] = 1318,
                    [17] = 1318,
                    [18] = 57,
                    [19] = 57,
                    [20] = 1086,
                },
                ["anchorMapOffset_x"] = 0,
                ["savedGold"] = 663182,
                ["pos_y"] = -4,
                ["Scale"] = 1,
                ["currentZoneAlwaysTop"] = false,
                ["FavoritePlayerStatusNotification"] = true,
                ["unlockingLessChatOutput"] = false,
                ["hidePublicDungeons"] = false,
                ["closeOnPorting"] = true,
                ["pos_x"] = 1646,
                ["HintOfflineWhisper"] = true,
                ["initialTimeStamp"] = 1718883038,
                ["autoRefreshFreq"] = 5,
                ["AutoPortFreq"] = 300,
                ["chatButtonHorizontalOffset"] = 0,
                ["numberLines"] = 16,
                ["showOfflineReminder"] = true,
                ["showNumberPlayers"] = true,
                ["currentViewedZoneAlwaysTop"] = false,
                ["anchorOnMap"] = true,
                ["hideOwnHouses"] = false,
                ["surveyMapsNotification"] = false,
                ["chatOutputAdditional"] = true,
                ["usePanAndZoom"] = true,
                ["chatOutputUnlock"] = false,
                ["onlyMaps"] = false,
                ["autoRefresh"] = true,
                ["showZonesWithoutPlayers2"] = false,
                ["fixedWindow"] = false,
                ["hideHouses"] = false,
                ["anchorMapOffset_y"] = 0,
                ["hideOthers"] = true,
                ["totalPortCounter"] = 2387,
                ["pos_MapScene_x"] = 138,
                ["showTeleportAnimation"] = true,
                ["surveyMapsNotificationSound"] = true,
                ["searchCharacterNames"] = false,
                ["secondLanguage"] = 1,
                ["hideClosedDungeons"] = true,
                ["pos_MapScene_y"] = 31,
                ["zoneOnceOnly"] = true,
                ["ShowOnMapOpen"] = true,
                ["useMapPing"] = false,
                ["autoUnlockChatLogging"] = false,
                ["version"] = 2,
                ["wayshrineTravelAutoConfirm"] = false,
                ["showContextMenuIcons"] = true,
                ["portCounterPerZone"] = 
                {
                    [1154] = 2,
                    [3] = 53,
                    [1413] = 4,
                    [1286] = 3,
                    [1415] = 3,
                    [1160] = 26,
                    [137] = 4,
                    [138] = 3,
                    [1548] = 5,
                    [1165] = 1,
                    [1166] = 1,
                    [1168] = 2,
                    [19] = 120,
                    [20] = 15,
                    [534] = 1,
                    [535] = 14,
                    [280] = 1,
                    [537] = 3,
                    [1051] = 5,
                    [284] = 4,
                    [1186] = 1,
                    [1443] = 67,
                    [933] = 1,
                    [1318] = 138,
                    [1063] = 1,
                    [41] = 61,
                    [1196] = 3,
                    [557] = 1,
                    [816] = 1,
                    [306] = 1,
                    [1559] = 4,
                    [308] = 3,
                    [382] = 30,
                    [1021] = 3,
                    [1463] = 3,
                    [1208] = 1,
                    [57] = 528,
                    [58] = 15,
                    [1467] = 2,
                    [1020] = 1,
                    [919] = 1,
                    [1086] = 55,
                    [1089] = 1,
                    [1344] = 5,
                    [705] = 1,
                    [1090] = 1,
                    [134] = 1,
                    [888] = 62,
                    [142] = 2,
                    [1478] = 12,
                    [1337] = 1,
                    [124] = 3,
                    [396] = 1,
                    [1416] = 1,
                    [918] = 1,
                    [1414] = 20,
                    [1027] = 12,
                    [725] = 1,
                    [975] = 2,
                    [341] = 2,
                    [849] = 128,
                    [1261] = 38,
                    [1260] = 3,
                    [980] = 3,
                    [981] = 1,
                    [726] = 2,
                    [1494] = 1,
                    [169] = 2,
                    [1497] = 1,
                    [92] = 28,
                    [347] = 12,
                    [860] = 1,
                    [1000] = 2,
                    [1502] = 22,
                    [487] = 1,
                    [823] = 9,
                    [1121] = 3,
                    [1207] = 6,
                    [931] = 1,
                    [1383] = 4,
                    [101] = 176,
                    [486] = 1,
                    [103] = 35,
                    [104] = 142,
                    [1129] = 1,
                    [1514] = 1,
                    [1259] = 2,
                    [108] = 17,
                    [1133] = 4,
                    [1390] = 2,
                    [1263] = 15,
                    [1008] = 1,
                    [281] = 7,
                    [882] = 1,
                    [1011] = 37,
                    [1282] = 5,
                    [117] = 54,
                    [684] = 13,
                    [1466] = 2,
                    [1528] = 1,
                    [1338] = 2,
                    [1530] = 1,
                    [1427] = 1,
                    [636] = 1,
                    [381] = 77,
                    [638] = 1,
                    [383] = 199,
                },
                ["infoBMUGuild"] = true,
            },
            ["8796093077977317"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Simmy Seek Snow",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
        },
        ["@YYDS1214"] = 
        {
            ["8796093077165965"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Junjunya",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["showEndlessDungeons"] = true,
                    ["showDungeons"] = true,
                    ["GPtoggleShowUpdateNum"] = false,
                    ["GPtoggleShowAcronymUpdateName"] = false,
                    ["showArenas"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077181579"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "A qiya",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077616617"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "shiaqi",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077153837"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Yang Yyds",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077181565"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Aqiya",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077181587"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "a qi ya",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["8796093077595053"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "aqi ya",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
            ["$AccountWide"] = 
            {
                ["hideDelves"] = false,
                ["chatOutputFastTravel"] = true,
                ["infoFavoritePlayerStatusNotification"] = false,
                ["showOpenButtonOnMap"] = true,
                ["HideOnMapClose"] = true,
                ["infoSurveyMapsNotification"] = false,
                ["closeOnPorting"] = true,
                ["windowStay"] = false,
                ["hidePVP"] = true,
                ["focusZoneSearchOnOpening"] = false,
                ["chatButton"] = true,
                ["lastPortedZones"] = 
                {
                },
                ["pos_MapScene_y"] = 63,
                ["savedGold"] = 0,
                ["Scale"] = 1,
                ["FavoritePlayerStatusNotification"] = true,
                ["pos_x"] = -15,
                ["hidePublicDungeons"] = false,
                ["useMapPing"] = false,
                ["portCounterPerZone"] = 
                {
                },
                ["HintOfflineWhisper"] = true,
                ["chatOutputUnlock"] = true,
                ["autoRefreshFreq"] = 5,
                ["fixedWindow"] = false,
                ["chatButtonHorizontalOffset"] = 0,
                ["pos_y"] = 63,
                ["onlyMaps"] = false,
                ["showNumberPlayers"] = true,
                ["currentViewedZoneAlwaysTop"] = false,
                ["anchorOnMap"] = true,
                ["secondLanguage"] = 1,
                ["surveyMapsNotification"] = false,
                ["chatOutputAdditional"] = true,
                ["showTeleportAnimation"] = true,
                ["currentZoneAlwaysTop"] = false,
                ["formatZoneName"] = false,
                ["autoRefresh"] = true,
                ["showZonesWithoutPlayers2"] = true,
                ["zoneOnceOnly"] = true,
                ["hideHouses"] = false,
                ["anchorMapOffset_y"] = 0,
                ["hideOthers"] = true,
                ["hideClosedDungeons"] = true,
                ["pos_MapScene_x"] = -15,
                ["anchorMapOffset_x"] = 0,
                ["surveyMapsNotificationSound"] = true,
                ["searchCharacterNames"] = false,
                ["initialTimeStamp"] = 1776136986,
                ["AutoPortFreq"] = 300,
                ["hideOwnHouses"] = false,
                ["usePanAndZoom"] = true,
                ["ShowOnMapOpen"] = true,
                ["numberLines"] = 10,
                ["totalPortCounter"] = 0,
                ["version"] = 2,
                ["wayshrineTravelAutoConfirm"] = false,
                ["showOfflineReminder"] = true,
                ["showContextMenuIcons"] = true,
                ["infoBMUGuild"] = true,
            },
            ["8796093077181623"] = 
            {
                ["defaultTab"] = 0,
                ["ptfHouseZoneNames"] = false,
                ["$LastCharacterName"] = "Aqi Yaa",
                ["dungeonFinder"] = 
                {
                    ["sortByAcronym"] = false,
                    ["sortByReleaseASC"] = true,
                    ["showTrials"] = true,
                    ["showGroupArenas"] = true,
                    ["sortByReleaseDESC"] = false,
                    ["toggleShowZoneNameDungeonName"] = false,
                    ["showArenas"] = true,
                    ["showDungeons"] = true,
                    ["showEndlessDungeons"] = true,
                    ["toggleShowAcronymUpdateName"] = false,
                },
                ["displayMaps"] = 
                {
                    ["clue"] = true,
                    ["treasure"] = true,
                    ["enchanter"] = true,
                    ["jewelry"] = true,
                    ["clothier"] = true,
                    ["woodworker"] = true,
                    ["alchemist"] = true,
                    ["blacksmith"] = true,
                },
                ["showAllDelves"] = false,
                ["displayAntiquityLeads"] = 
                {
                    ["completed"] = true,
                    ["srcyable"] = true,
                    ["scried"] = true,
                },
                ["displayCounterPanel"] = true,
                ["version"] = 3,
                ["houseNickNames"] = false,
                ["sorting"] = 2,
                ["scanBankForMaps"] = true,
                ["houseZoneNames"] = false,
            },
        },
    },
    ["EU Megaserver"] = 
    {
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["houseFurnitureCount_LII"] = 
                {
                    [111] = 63,
                },
                ["favoriteDungeon"] = 0,
                ["favoriteListWayshrines"] = 
                {
                },
                ["houseCustomSorting"] = 
                {
                },
                ["lastofflineReminder"] = 1632859025,
                ["favoriteListPlayers"] = 
                {
                },
                ["version"] = 3,
                ["favoriteListZones"] = 
                {
                },
                ["zoneSpecificHouses"] = 
                {
                },
                ["prioritizationSource"] = 
                {
                    [1] = 2,
                    [2] = 3,
                    [3] = 4,
                    [4] = 5,
                    [5] = 6,
                    [6] = 7,
                },
            },
        },
    },
    ["NA Megaserver"] = 
    {
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["houseFurnitureCount_LII"] = 
                {
                },
                ["favoriteDungeon"] = 0,
                ["favoriteListPlayers"] = 
                {
                },
                ["version"] = 3,
                ["houseCustomSorting"] = 
                {
                },
                ["favoriteListZones"] = 
                {
                },
                ["lastofflineReminder"] = 1632859025,
                ["prioritizationSource"] = 
                {
                    [1] = 2,
                    [2] = 3,
                    [3] = 4,
                    [4] = 5,
                    [5] = 6,
                    [6] = 7,
                },
            },
        },
        ["@Kankerkop"] = 
        {
            ["$AccountWide"] = 
            {
                ["houseFurnitureCount_LII"] = 
                {
                    [3] = 8,
                },
                ["favoriteDungeon"] = 0,
                ["favoriteListWayshrines"] = 
                {
                },
                ["houseCustomSorting"] = 
                {
                },
                ["lastofflineReminder"] = 1765731451,
                ["favoriteListPlayers"] = 
                {
                },
                ["version"] = 3,
                ["favoriteListZones"] = 
                {
                },
                ["zoneSpecificHouses"] = 
                {
                },
                ["prioritizationSource"] = 
                {
                    [1] = 2,
                    [2] = 3,
                    [3] = 4,
                    [4] = 5,
                    [5] = 6,
                    [6] = 7,
                },
            },
        },
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["houseFurnitureCount_LII"] = 
                {
                    [34] = 35,
                    [99] = 307,
                    [4] = 62,
                    [5] = 2,
                    [6] = 9,
                    [10] = 70,
                    [13] = 46,
                    [110] = 327,
                    [111] = 58,
                    [112] = 323,
                    [114] = 280,
                    [100] = 30,
                    [30] = 187,
                    [118] = 1,
                    [87] = 30,
                    [68] = 1,
                    [25] = 47,
                    [121] = 192,
                    [102] = 290,
                    [124] = 227,
                    [109] = 1,
                    [62] = 382,
                    [95] = 1,
                },
                ["favoriteDungeon"] = 0,
                ["favoriteListWayshrines"] = 
                {
                },
                ["houseCustomSorting"] = 
                {
                    [99] = 99,
                },
                ["lastofflineReminder"] = 1781446717,
                ["favoriteListPlayers"] = 
                {
                },
                ["version"] = 3,
                ["favoriteListZones"] = 
                {
                },
                ["zoneSpecificHouses"] = 
                {
                },
                ["prioritizationSource"] = 
                {
                    [1] = 2,
                    [2] = 3,
                    [3] = 4,
                    [4] = 5,
                    [5] = 6,
                    [6] = 7,
                },
            },
        },
        ["@YYDS1214"] = 
        {
            ["$AccountWide"] = 
            {
                ["houseFurnitureCount_LII"] = 
                {
                },
                ["favoriteDungeon"] = 0,
                ["favoriteListWayshrines"] = 
                {
                },
                ["houseCustomSorting"] = 
                {
                },
                ["lastofflineReminder"] = 1632859025,
                ["favoriteListPlayers"] = 
                {
                },
                ["version"] = 3,
                ["favoriteListZones"] = 
                {
                },
                ["zoneSpecificHouses"] = 
                {
                },
                ["prioritizationSource"] = 
                {
                    [1] = 2,
                    [2] = 3,
                    [3] = 4,
                    [4] = 5,
                    [5] = 6,
                    [6] = 7,
                },
            },
        },
    },
}
