HowToCloudrestVariables =
{
    ["Default"] = 
    {
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["FontSize_CrushingDarkness_Next"] = 32,
                ["Size_MiniFrame"] = 5,
                ["overloadColorChoice"] = 4,
                ["Enable"] = 
                {
                    ["CrushingDarkness_Kite"] = true,
                    ["MaliciousSphere_Tracking"] = true,
                    ["RazorThorns"] = true,
                    ["MaliciousSphere_Announcement"] = true,
                    ["Spears"] = true,
                    ["Portal"] = true,
                    ["ChillingComet"] = true,
                    ["CrushingDarkness_Next"] = true,
                    ["Overload_Overlay"] = true,
                    ["Overload"] = true,
                    ["Overload_Tabulation"] = true,
                    ["DarkTalons"] = true,
                    ["Flare"] = true,
                    ["MiniSkill"] = true,
                    ["MiniBash"] = true,
                    ["MiniFrame"] = true,
                    ["HA"] = false,
                    ["Hoarfrost"] = true,
                    ["MiniJump"] = true,
                    ["ZmajaJump"] = true,
                    ["Creeper_Announcement"] = true,
                    ["ReleHA"] = true,
                    ["ShadowSplash"] = true,
                    ["Portal_Announcement"] = true,
                    ["Announcement_MiniBash"] = true,
                    ["BanefulMark"] = true,
                    ["MalevolentCores"] = true,
                    ["MaliciousSphere_Execute"] = true,
                    ["MaliciousSphere_Timer"] = true,
                },
                ["OverloadFrequency"] = 5,
                ["FontSize_ReleHA"] = 32,
                ["FontSize_ChillingComet"] = 40,
                ["FontSize_ZmajaJump"] = 40,
                ["FontSize_CrushingDarkness_Kite"] = 40,
                ["FontSize_Rooted"] = 32,
                ["FontSize_Overload"] = 50,
                ["version"] = 1,
                ["FontSize_Hoarfrost"] = 40,
                ["FontSize_HA"] = 32,
                ["FontSize_MaliciousSphere_Announcement"] = 40,
                ["OffsetY"] = 
                {
                    ["CrushingDarkness_Kite"] = 400,
                    ["MaliciousSphere_Tracking"] = 545,
                    ["MaliciousSphere_Announcement"] = 440,
                    ["Portal"] = 460,
                    ["ChillingComet"] = 640,
                    ["CrushingDarkness_Next"] = 495,
                    ["Overload"] = 300,
                    ["MaliciousSphere_Timer"] = 525,
                    ["ShadowSplash"] = 640,
                    ["MiniFrame"] = 325,
                    ["Rooted"] = 610,
                    ["HA"] = 575,
                    ["Hoarfrost"] = 355,
                    ["ZmajaJump"] = 145,
                    ["Portal_Announcement"] = 440,
                    ["Announcement_MiniBash"] = 670,
                    ["BanefulMark"] = 145,
                    ["Creeper_Announcement"] = 440,
                    ["ReleHA"] = 575,
                    ["Flare"] = 400,
                },
                ["overloadColor"] = 
                {
                    [1] = 1,
                    [2] = 0,
                    [3] = 1,
                },
                ["FontSize_Portal_Announcement"] = 40,
                ["FontSize_Flare"] = 50,
                ["FontSize_MaliciousSphere_Tracking"] = 48,
                ["FontSize_MaliciousSphere_Timer"] = 32,
                ["Sizes_MiniFrame"] = 
                {
                    [1] = 
                    {
                        ["TopRow_OffsetX"] = 85,
                        ["Mini_OffsetY"] = 24,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 20,
                    },
                    [2] = 
                    {
                        ["TopRow_OffsetX"] = 95,
                        ["Mini_OffsetY"] = 25,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 22,
                    },
                    [3] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 29,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 24,
                    },
                    [4] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 30,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 26,
                    },
                    [5] = 
                    {
                        ["TopRow_OffsetX"] = 120,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 28,
                    },
                    [6] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 30,
                    },
                    [7] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 38,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 32,
                    },
                    [8] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 40,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 34,
                    },
                    [9] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 43,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 36,
                    },
                    [10] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 44,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 38,
                    },
                    [11] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 47,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 40,
                    },
                    [12] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 50,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 42,
                    },
                },
                ["OffsetX"] = 
                {
                    ["CrushingDarkness_Kite"] = 885,
                    ["MaliciousSphere_Tracking"] = 970,
                    ["MaliciousSphere_Announcement"] = 815,
                    ["Portal"] = 1290,
                    ["ChillingComet"] = 810,
                    ["CrushingDarkness_Next"] = 1290,
                    ["Overload"] = 805,
                    ["MaliciousSphere_Timer"] = 1290,
                    ["ShadowSplash"] = 810,
                    ["MiniFrame"] = 1285,
                    ["Rooted"] = 875,
                    ["HA"] = 885,
                    ["Hoarfrost"] = 805,
                    ["ZmajaJump"] = 830,
                    ["Portal_Announcement"] = 815,
                    ["Announcement_MiniBash"] = 785,
                    ["BanefulMark"] = 830,
                    ["Creeper_Announcement"] = 815,
                    ["ReleHA"] = 890,
                    ["Flare"] = 960,
                },
                ["defaultSettingsChoice"] = "Show Everything",
                ["FontSize_Creeper_Announcement"] = 32,
                ["FontSize_BashAnnouncement"] = 32,
                ["FontSize_Portal"] = 32,
                ["FontSize_ShadowSplash"] = 32,
                ["FontSize_BanefulMark"] = 40,
            },
        },
        ["@Kankerkop"] = 
        {
            ["$AccountWide"] = 
            {
                ["FontSize_CrushingDarkness_Next"] = 32,
                ["Size_MiniFrame"] = 5,
                ["overloadColorChoice"] = 4,
                ["Enable"] = 
                {
                    ["CrushingDarkness_Kite"] = true,
                    ["MaliciousSphere_Tracking"] = true,
                    ["RazorThorns"] = true,
                    ["MaliciousSphere_Announcement"] = true,
                    ["Spears"] = true,
                    ["Portal"] = true,
                    ["ChillingComet"] = true,
                    ["CrushingDarkness_Next"] = true,
                    ["Overload_Overlay"] = true,
                    ["Overload"] = true,
                    ["Overload_Tabulation"] = true,
                    ["DarkTalons"] = true,
                    ["Flare"] = true,
                    ["MiniSkill"] = true,
                    ["MiniBash"] = true,
                    ["MiniFrame"] = true,
                    ["HA"] = false,
                    ["Hoarfrost"] = true,
                    ["MiniJump"] = true,
                    ["ZmajaJump"] = true,
                    ["Creeper_Announcement"] = true,
                    ["ReleHA"] = true,
                    ["ShadowSplash"] = true,
                    ["Portal_Announcement"] = true,
                    ["Announcement_MiniBash"] = true,
                    ["BanefulMark"] = true,
                    ["MalevolentCores"] = true,
                    ["MaliciousSphere_Execute"] = true,
                    ["MaliciousSphere_Timer"] = true,
                },
                ["OverloadFrequency"] = 5,
                ["FontSize_ReleHA"] = 32,
                ["FontSize_ChillingComet"] = 40,
                ["FontSize_ZmajaJump"] = 40,
                ["FontSize_CrushingDarkness_Kite"] = 40,
                ["FontSize_Rooted"] = 32,
                ["FontSize_Overload"] = 50,
                ["version"] = 1,
                ["FontSize_Hoarfrost"] = 40,
                ["FontSize_HA"] = 32,
                ["FontSize_MaliciousSphere_Announcement"] = 40,
                ["OffsetY"] = 
                {
                    ["CrushingDarkness_Kite"] = 400,
                    ["MaliciousSphere_Tracking"] = 545,
                    ["MaliciousSphere_Announcement"] = 440,
                    ["Portal"] = 460,
                    ["ChillingComet"] = 640,
                    ["CrushingDarkness_Next"] = 495,
                    ["Overload"] = 300,
                    ["MaliciousSphere_Timer"] = 525,
                    ["ShadowSplash"] = 640,
                    ["MiniFrame"] = 325,
                    ["Rooted"] = 610,
                    ["HA"] = 575,
                    ["Hoarfrost"] = 355,
                    ["ZmajaJump"] = 145,
                    ["Portal_Announcement"] = 440,
                    ["Announcement_MiniBash"] = 670,
                    ["BanefulMark"] = 145,
                    ["Creeper_Announcement"] = 440,
                    ["ReleHA"] = 575,
                    ["Flare"] = 400,
                },
                ["overloadColor"] = 
                {
                    [1] = 1,
                    [2] = 0,
                    [3] = 1,
                },
                ["FontSize_Portal_Announcement"] = 40,
                ["FontSize_Flare"] = 50,
                ["FontSize_MaliciousSphere_Tracking"] = 48,
                ["FontSize_MaliciousSphere_Timer"] = 32,
                ["Sizes_MiniFrame"] = 
                {
                    [1] = 
                    {
                        ["TopRow_OffsetX"] = 85,
                        ["Mini_OffsetY"] = 24,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 20,
                    },
                    [2] = 
                    {
                        ["TopRow_OffsetX"] = 95,
                        ["Mini_OffsetY"] = 25,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 22,
                    },
                    [3] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 29,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 24,
                    },
                    [4] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 30,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 26,
                    },
                    [5] = 
                    {
                        ["TopRow_OffsetX"] = 120,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 28,
                    },
                    [6] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 30,
                    },
                    [7] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 38,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 32,
                    },
                    [8] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 40,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 34,
                    },
                    [9] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 43,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 36,
                    },
                    [10] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 44,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 38,
                    },
                    [11] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 47,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 40,
                    },
                    [12] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 50,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 42,
                    },
                },
                ["OffsetX"] = 
                {
                    ["CrushingDarkness_Kite"] = 885,
                    ["MaliciousSphere_Tracking"] = 970,
                    ["MaliciousSphere_Announcement"] = 815,
                    ["Portal"] = 1290,
                    ["ChillingComet"] = 810,
                    ["CrushingDarkness_Next"] = 1290,
                    ["Overload"] = 805,
                    ["MaliciousSphere_Timer"] = 1290,
                    ["ShadowSplash"] = 810,
                    ["MiniFrame"] = 1285,
                    ["Rooted"] = 875,
                    ["HA"] = 885,
                    ["Hoarfrost"] = 805,
                    ["ZmajaJump"] = 830,
                    ["Portal_Announcement"] = 815,
                    ["Announcement_MiniBash"] = 785,
                    ["BanefulMark"] = 830,
                    ["Creeper_Announcement"] = 815,
                    ["ReleHA"] = 890,
                    ["Flare"] = 960,
                },
                ["defaultSettingsChoice"] = "Show Everything",
                ["FontSize_Creeper_Announcement"] = 32,
                ["FontSize_BashAnnouncement"] = 32,
                ["FontSize_Portal"] = 32,
                ["FontSize_ShadowSplash"] = 32,
                ["FontSize_BanefulMark"] = 40,
            },
        },
        ["@YYDS1214"] = 
        {
            ["$AccountWide"] = 
            {
                ["FontSize_CrushingDarkness_Next"] = 32,
                ["Size_MiniFrame"] = 5,
                ["overloadColorChoice"] = 4,
                ["Enable"] = 
                {
                    ["CrushingDarkness_Kite"] = true,
                    ["MaliciousSphere_Tracking"] = true,
                    ["RazorThorns"] = true,
                    ["MaliciousSphere_Announcement"] = true,
                    ["Spears"] = true,
                    ["Portal"] = true,
                    ["ChillingComet"] = true,
                    ["CrushingDarkness_Next"] = true,
                    ["Overload_Overlay"] = true,
                    ["Overload"] = true,
                    ["Overload_Tabulation"] = true,
                    ["DarkTalons"] = true,
                    ["Flare"] = true,
                    ["MiniSkill"] = true,
                    ["MiniBash"] = true,
                    ["MiniFrame"] = true,
                    ["HA"] = false,
                    ["Hoarfrost"] = true,
                    ["MiniJump"] = true,
                    ["ZmajaJump"] = true,
                    ["Creeper_Announcement"] = true,
                    ["ReleHA"] = true,
                    ["ShadowSplash"] = true,
                    ["Portal_Announcement"] = true,
                    ["Announcement_MiniBash"] = true,
                    ["BanefulMark"] = true,
                    ["MalevolentCores"] = true,
                    ["MaliciousSphere_Execute"] = true,
                    ["MaliciousSphere_Timer"] = true,
                },
                ["OverloadFrequency"] = 5,
                ["FontSize_ReleHA"] = 32,
                ["FontSize_ChillingComet"] = 40,
                ["FontSize_ZmajaJump"] = 40,
                ["FontSize_CrushingDarkness_Kite"] = 40,
                ["FontSize_Rooted"] = 32,
                ["FontSize_Overload"] = 50,
                ["version"] = 1,
                ["FontSize_Hoarfrost"] = 40,
                ["FontSize_HA"] = 32,
                ["FontSize_MaliciousSphere_Announcement"] = 40,
                ["OffsetY"] = 
                {
                    ["CrushingDarkness_Kite"] = 400,
                    ["MaliciousSphere_Tracking"] = 545,
                    ["MaliciousSphere_Announcement"] = 440,
                    ["Portal"] = 460,
                    ["ChillingComet"] = 640,
                    ["CrushingDarkness_Next"] = 495,
                    ["Overload"] = 300,
                    ["MaliciousSphere_Timer"] = 525,
                    ["ShadowSplash"] = 640,
                    ["MiniFrame"] = 325,
                    ["Rooted"] = 610,
                    ["HA"] = 575,
                    ["Hoarfrost"] = 355,
                    ["ZmajaJump"] = 145,
                    ["Portal_Announcement"] = 440,
                    ["Announcement_MiniBash"] = 670,
                    ["BanefulMark"] = 145,
                    ["Creeper_Announcement"] = 440,
                    ["ReleHA"] = 575,
                    ["Flare"] = 400,
                },
                ["overloadColor"] = 
                {
                    [1] = 1,
                    [2] = 0,
                    [3] = 1,
                },
                ["FontSize_Portal_Announcement"] = 40,
                ["FontSize_Flare"] = 50,
                ["FontSize_MaliciousSphere_Tracking"] = 48,
                ["FontSize_MaliciousSphere_Timer"] = 32,
                ["Sizes_MiniFrame"] = 
                {
                    [1] = 
                    {
                        ["TopRow_OffsetX"] = 85,
                        ["Mini_OffsetY"] = 24,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 20,
                    },
                    [2] = 
                    {
                        ["TopRow_OffsetX"] = 95,
                        ["Mini_OffsetY"] = 25,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 22,
                    },
                    [3] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 29,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 24,
                    },
                    [4] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 30,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 26,
                    },
                    [5] = 
                    {
                        ["TopRow_OffsetX"] = 120,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 28,
                    },
                    [6] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 30,
                    },
                    [7] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 38,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 32,
                    },
                    [8] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 40,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 34,
                    },
                    [9] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 43,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 36,
                    },
                    [10] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 44,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 38,
                    },
                    [11] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 47,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 40,
                    },
                    [12] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 50,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 42,
                    },
                },
                ["OffsetX"] = 
                {
                    ["CrushingDarkness_Kite"] = 885,
                    ["MaliciousSphere_Tracking"] = 970,
                    ["MaliciousSphere_Announcement"] = 815,
                    ["Portal"] = 1290,
                    ["ChillingComet"] = 810,
                    ["CrushingDarkness_Next"] = 1290,
                    ["Overload"] = 805,
                    ["MaliciousSphere_Timer"] = 1290,
                    ["ShadowSplash"] = 810,
                    ["MiniFrame"] = 1285,
                    ["Rooted"] = 875,
                    ["HA"] = 885,
                    ["Hoarfrost"] = 805,
                    ["ZmajaJump"] = 830,
                    ["Portal_Announcement"] = 815,
                    ["Announcement_MiniBash"] = 785,
                    ["BanefulMark"] = 830,
                    ["Creeper_Announcement"] = 815,
                    ["ReleHA"] = 890,
                    ["Flare"] = 960,
                },
                ["defaultSettingsChoice"] = "Show Everything",
                ["FontSize_Creeper_Announcement"] = 32,
                ["FontSize_BashAnnouncement"] = 32,
                ["FontSize_Portal"] = 32,
                ["FontSize_ShadowSplash"] = 32,
                ["FontSize_BanefulMark"] = 40,
            },
        },
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["FontSize_CrushingDarkness_Next"] = 32,
                ["Size_MiniFrame"] = 5,
                ["overloadColorChoice"] = 4,
                ["Enable"] = 
                {
                    ["CrushingDarkness_Kite"] = true,
                    ["MaliciousSphere_Tracking"] = true,
                    ["RazorThorns"] = true,
                    ["MaliciousSphere_Announcement"] = true,
                    ["Spears"] = true,
                    ["Portal"] = true,
                    ["ChillingComet"] = true,
                    ["CrushingDarkness_Next"] = true,
                    ["Overload_Overlay"] = true,
                    ["Overload"] = true,
                    ["Overload_Tabulation"] = true,
                    ["DarkTalons"] = true,
                    ["Flare"] = true,
                    ["MiniSkill"] = true,
                    ["MiniBash"] = true,
                    ["MiniFrame"] = true,
                    ["HA"] = false,
                    ["Hoarfrost"] = true,
                    ["MiniJump"] = true,
                    ["ZmajaJump"] = true,
                    ["Creeper_Announcement"] = true,
                    ["ReleHA"] = true,
                    ["ShadowSplash"] = true,
                    ["Portal_Announcement"] = true,
                    ["Announcement_MiniBash"] = true,
                    ["BanefulMark"] = true,
                    ["MalevolentCores"] = true,
                    ["MaliciousSphere_Execute"] = true,
                    ["MaliciousSphere_Timer"] = true,
                },
                ["OverloadFrequency"] = 5,
                ["FontSize_ReleHA"] = 32,
                ["FontSize_ChillingComet"] = 40,
                ["FontSize_ZmajaJump"] = 40,
                ["FontSize_CrushingDarkness_Kite"] = 40,
                ["FontSize_Rooted"] = 32,
                ["FontSize_Overload"] = 50,
                ["version"] = 1,
                ["FontSize_Hoarfrost"] = 40,
                ["FontSize_HA"] = 32,
                ["FontSize_MaliciousSphere_Announcement"] = 40,
                ["OffsetY"] = 
                {
                    ["CrushingDarkness_Kite"] = 895,
                    ["MaliciousSphere_Tracking"] = 548,
                    ["MaliciousSphere_Announcement"] = 440,
                    ["Portal"] = 279,
                    ["ChillingComet"] = 781,
                    ["CrushingDarkness_Next"] = 494,
                    ["Overload"] = 643,
                    ["MaliciousSphere_Timer"] = 525,
                    ["ShadowSplash"] = 640,
                    ["MiniFrame"] = 328,
                    ["Rooted"] = 324,
                    ["HA"] = 575,
                    ["Hoarfrost"] = 424,
                    ["ZmajaJump"] = 506,
                    ["Portal_Announcement"] = 440,
                    ["Announcement_MiniBash"] = 670,
                    ["BanefulMark"] = 577,
                    ["Creeper_Announcement"] = 840,
                    ["ReleHA"] = 722,
                    ["Flare"] = 240,
                },
                ["overloadColor"] = 
                {
                    [1] = 1,
                    [2] = 0,
                    [3] = 1,
                },
                ["FontSize_Portal_Announcement"] = 40,
                ["FontSize_Flare"] = 50,
                ["FontSize_MaliciousSphere_Tracking"] = 48,
                ["FontSize_MaliciousSphere_Timer"] = 32,
                ["Sizes_MiniFrame"] = 
                {
                    [1] = 
                    {
                        ["TopRow_OffsetX"] = 85,
                        ["Mini_OffsetY"] = 24,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 20,
                    },
                    [2] = 
                    {
                        ["TopRow_OffsetX"] = 95,
                        ["Mini_OffsetY"] = 25,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 22,
                    },
                    [3] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 29,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 24,
                    },
                    [4] = 
                    {
                        ["TopRow_OffsetX"] = 105,
                        ["Mini_OffsetY"] = 30,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 26,
                    },
                    [5] = 
                    {
                        ["TopRow_OffsetX"] = 120,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 28,
                    },
                    [6] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 34,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 30,
                    },
                    [7] = 
                    {
                        ["TopRow_OffsetX"] = 135,
                        ["Mini_OffsetY"] = 38,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 32,
                    },
                    [8] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 40,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 34,
                    },
                    [9] = 
                    {
                        ["TopRow_OffsetX"] = 150,
                        ["Mini_OffsetY"] = 43,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 36,
                    },
                    [10] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 44,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 38,
                    },
                    [11] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 47,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 40,
                    },
                    [12] = 
                    {
                        ["TopRow_OffsetX"] = 170,
                        ["Mini_OffsetY"] = 50,
                        ["Mini_OffsetX"] = 5,
                        ["TopRow_OffsetY"] = 0,
                        ["fontSize"] = 42,
                    },
                },
                ["OffsetX"] = 
                {
                    ["CrushingDarkness_Kite"] = 645,
                    ["MaliciousSphere_Tracking"] = 993,
                    ["MaliciousSphere_Announcement"] = 815,
                    ["Portal"] = 1756,
                    ["ChillingComet"] = 674,
                    ["CrushingDarkness_Next"] = 1290,
                    ["Overload"] = 722,
                    ["MaliciousSphere_Timer"] = 1290,
                    ["ShadowSplash"] = 810,
                    ["MiniFrame"] = 1755,
                    ["Rooted"] = 1144,
                    ["HA"] = 885,
                    ["Hoarfrost"] = 664,
                    ["ZmajaJump"] = 705,
                    ["Portal_Announcement"] = 815,
                    ["Announcement_MiniBash"] = 785,
                    ["BanefulMark"] = 685,
                    ["Creeper_Announcement"] = 644,
                    ["ReleHA"] = 668,
                    ["Flare"] = 1087,
                },
                ["defaultSettingsChoice"] = "显示所有",
                ["FontSize_Creeper_Announcement"] = 32,
                ["FontSize_BashAnnouncement"] = 32,
                ["FontSize_Portal"] = 32,
                ["FontSize_ShadowSplash"] = 32,
                ["FontSize_BanefulMark"] = 40,
            },
        },
    },
}
