JackOfAllTradesData =
{
    ["Default"] = 
    {
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["warnings"] = 
                {
                    ["meticulousDisassembly"] = false,
                    ["plentifulHarvest"] = false,
                    ["anglersInstinct"] = false,
                    ["homemaker"] = false,
                    ["infamous"] = false,
                    ["professionalUpkeep"] = false,
                    ["cutpursesArt"] = false,
                    ["masterGatherer"] = false,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["rationer"] = false,
                    ["reelTechnique"] = false,
                    ["liquidEfficiency"] = false,
                    ["treasureHunter"] = false,
                    ["sustainingShadows"] = false,
                },
                ["slotSkillsAfterCooldownEnds"] = true,
                ["slotMdWhilstDoingWrits"] = true,
                ["slotLeTrashPots"] = true,
                ["textureNotification"] = true,
                ["alertNotification"] = false,
                ["slotRationerInGrindSpot"] = true,
                ["altertedAfterCooldownOver"] = false,
                ["slotThInDungeon"] = false,
                ["debug"] = false,
                ["enable"] = 
                {
                    ["meticulousDisassembly"] = true,
                    ["plentifulHarvest"] = true,
                    ["anglersInstinct"] = true,
                    ["homemaker"] = true,
                    ["infamous"] = true,
                    ["professionalUpkeep"] = true,
                    ["cutpursesArt"] = true,
                    ["masterGatherer"] = true,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["rationer"] = true,
                    ["reelTechnique"] = true,
                    ["liquidEfficiency"] = true,
                    ["treasureHunter"] = true,
                    ["sustainingShadows"] = true,
                },
                ["slotIndex"] = 
                {
                    ["meticulousDisassembly"] = 4,
                    ["plentifulHarvest"] = 3,
                    ["anglersInstinct"] = 3,
                    ["homemaker"] = 3,
                    ["infamous"] = 4,
                    ["professionalUpkeep"] = 4,
                    ["cutpursesArt"] = 4,
                    ["masterGatherer"] = 4,
                    ["warMount"] = 3,
                    ["giftedRider"] = 4,
                    ["rationer"] = 4,
                    ["reelTechnique"] = 4,
                    ["liquidEfficiency"] = 3,
                    ["treasureHunter"] = 4,
                    ["sustainingShadows"] = 3,
                },
                ["thHmPair"] = false,
                ["homemakerCorpses"] = false,
                ["notification"] = 
                {
                    ["meticulousDisassembly"] = true,
                    ["plentifulHarvest"] = true,
                    ["anglersInstinct"] = true,
                    ["homemaker"] = true,
                    ["infamous"] = true,
                    ["professionalUpkeep"] = true,
                    ["cutpursesArt"] = true,
                    ["masterGatherer"] = true,
                    ["warMount"] = true,
                    ["giftedRider"] = true,
                    ["rationer"] = true,
                    ["reelTechnique"] = true,
                    ["liquidEfficiency"] = true,
                    ["treasureHunter"] = true,
                    ["sustainingShadows"] = true,
                },
                ["version"] = 2,
                ["automaticallyAllocatePoints"] = false,
                ["showCooldownError"] = true,
                ["alertWarning"] = false,
                ["colour"] = 
                {
                    ["warnings"] = "|cba6a1a",
                    ["notifications"] = "|c638C29",
                },
            },
        },
        ["@Kankerkop"] = 
        {
            ["$AccountWide"] = 
            {
                ["warnings"] = 
                {
                    ["meticulousDisassembly"] = true,
                    ["plentifulHarvest"] = true,
                    ["anglersInstinct"] = false,
                    ["homemaker"] = true,
                    ["infamous"] = true,
                    ["professionalUpkeep"] = true,
                    ["cutpursesArt"] = true,
                    ["masterGatherer"] = false,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["rationer"] = true,
                    ["reelTechnique"] = false,
                    ["liquidEfficiency"] = true,
                    ["treasureHunter"] = true,
                    ["sustainingShadows"] = false,
                },
                ["slotSkillsAfterCooldownEnds"] = true,
                ["slotMdWhilstDoingWrits"] = true,
                ["slotLeTrashPots"] = true,
                ["textureNotification"] = true,
                ["alertNotification"] = false,
                ["slotRationerInGrindSpot"] = true,
                ["altertedAfterCooldownOver"] = false,
                ["slotThInDungeon"] = false,
                ["debug"] = false,
                ["enable"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["slotIndex"] = 
                {
                    ["masterGatherer"] = 4,
                    ["warMount"] = 3,
                    ["giftedRider"] = 4,
                    ["reelTechnique"] = 4,
                    ["anglersInstinct"] = 3,
                    ["sustainingShadows"] = 3,
                },
                ["homemakerCorpses"] = false,
                ["notification"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = true,
                    ["giftedRider"] = true,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["version"] = 2,
                ["showCooldownError"] = true,
                ["automaticallyAllocatePoints"] = false,
                ["alertWarning"] = false,
                ["colour"] = 
                {
                    ["warnings"] = "|cba6a1a",
                    ["notifications"] = "|c638C29",
                },
            },
        },
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["warnings"] = 
                {
                    ["meticulousDisassembly"] = false,
                    ["plentifulHarvest"] = false,
                    ["anglersInstinct"] = false,
                    ["homemaker"] = false,
                    ["infamous"] = false,
                    ["professionalUpkeep"] = false,
                    ["cutpursesArt"] = false,
                    ["masterGatherer"] = false,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["rationer"] = false,
                    ["reelTechnique"] = false,
                    ["liquidEfficiency"] = false,
                    ["treasureHunter"] = false,
                    ["sustainingShadows"] = false,
                },
                ["slotSkillsAfterCooldownEnds"] = true,
                ["slotMdWhilstDoingWrits"] = true,
                ["slotLeTrashPots"] = true,
                ["textureNotification"] = true,
                ["alertNotification"] = false,
                ["slotRationerInGrindSpot"] = true,
                ["altertedAfterCooldownOver"] = false,
                ["slotThInDungeon"] = false,
                ["debug"] = false,
                ["enable"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["slotIndex"] = 
                {
                    ["masterGatherer"] = 4,
                    ["warMount"] = 3,
                    ["giftedRider"] = 4,
                    ["reelTechnique"] = 4,
                    ["anglersInstinct"] = 3,
                    ["sustainingShadows"] = 3,
                },
                ["homemakerCorpses"] = false,
                ["notification"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = true,
                    ["giftedRider"] = true,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["version"] = 2,
                ["showCooldownError"] = true,
                ["automaticallyAllocatePoints"] = false,
                ["alertWarning"] = false,
                ["colour"] = 
                {
                    ["warnings"] = "|cba6a1a",
                    ["notifications"] = "|c638C29",
                },
            },
        },
        ["@YYDS1214"] = 
        {
            ["$AccountWide"] = 
            {
                ["warnings"] = 
                {
                    ["meticulousDisassembly"] = true,
                    ["plentifulHarvest"] = true,
                    ["anglersInstinct"] = false,
                    ["homemaker"] = true,
                    ["infamous"] = true,
                    ["professionalUpkeep"] = true,
                    ["cutpursesArt"] = true,
                    ["masterGatherer"] = false,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["rationer"] = true,
                    ["reelTechnique"] = false,
                    ["liquidEfficiency"] = true,
                    ["treasureHunter"] = true,
                    ["sustainingShadows"] = false,
                },
                ["slotSkillsAfterCooldownEnds"] = true,
                ["slotMdWhilstDoingWrits"] = true,
                ["slotLeTrashPots"] = true,
                ["textureNotification"] = true,
                ["alertNotification"] = false,
                ["slotRationerInGrindSpot"] = true,
                ["altertedAfterCooldownOver"] = false,
                ["slotThInDungeon"] = false,
                ["debug"] = false,
                ["enable"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = false,
                    ["giftedRider"] = false,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["slotIndex"] = 
                {
                    ["masterGatherer"] = 4,
                    ["warMount"] = 3,
                    ["giftedRider"] = 4,
                    ["reelTechnique"] = 4,
                    ["anglersInstinct"] = 3,
                    ["sustainingShadows"] = 3,
                },
                ["homemakerCorpses"] = false,
                ["notification"] = 
                {
                    ["masterGatherer"] = true,
                    ["warMount"] = true,
                    ["giftedRider"] = true,
                    ["reelTechnique"] = true,
                    ["anglersInstinct"] = true,
                    ["sustainingShadows"] = true,
                },
                ["version"] = 2,
                ["showCooldownError"] = true,
                ["automaticallyAllocatePoints"] = false,
                ["alertWarning"] = false,
                ["colour"] = 
                {
                    ["warnings"] = "|cba6a1a",
                    ["notifications"] = "|c638C29",
                },
            },
        },
    },
}
