LibCharacterData =
{
    ["__meta"] = 
    {
        ["libraryVersion"] = 3,
        ["type"] = 1,
        ["dataVersion"] = 1,
    },
    ["characters"] = 
    {
        ["8796093077622069"] = 
        {
            ["level"] = 50,
            ["name"] = "noobwick",
            ["rawName"] = "noobwick^Mx",
            ["classId"] = 4,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["id"] = "8796093077622069",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 5,
        },
        ["8796093077546265"] = 
        {
            ["level"] = 50,
            ["name"] = "Galen Chef Mike",
            ["rawName"] = "Galen Chef Mike^Mx",
            ["classId"] = 1,
            ["gender"] = 2,
            ["avaRank"] = 10,
            ["id"] = "8796093077546265",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 3,
        },
        ["8796093077181579"] = 
        {
            ["level"] = 50,
            ["name"] = "A qiya",
            ["rawName"] = "A qiya^Fx",
            ["classId"] = 6,
            ["gender"] = 1,
            ["avaRank"] = 0,
            ["raceId"] = 7,
            ["server"] = "NA Megaserver",
            ["alliance"] = 1,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077181579",
        },
        ["8796093077286759"] = 
        {
            ["level"] = 50,
            ["name"] = "Lumina Hoaying",
            ["rawName"] = "Lumina Hoaying^Fx",
            ["classId"] = 6,
            ["gender"] = 1,
            ["avaRank"] = 0,
            ["id"] = "8796093077286759",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 1,
        },
        ["8796093078078769"] = 
        {
            ["level"] = 50,
            ["name"] = "noobmiss",
            ["rawName"] = "noobmiss^Mx",
            ["classId"] = 3,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["id"] = "8796093078078769",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 5,
        },
        ["8796093077575525"] = 
        {
            ["level"] = 50,
            ["name"] = "Joyous Socks",
            ["rawName"] = "Joyous Socks^Mx",
            ["classId"] = 117,
            ["gender"] = 2,
            ["avaRank"] = 7,
            ["id"] = "8796093077575525",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 5,
        },
        ["8796093077181565"] = 
        {
            ["level"] = 50,
            ["name"] = "Aqiya",
            ["rawName"] = "Aqiya^Fx",
            ["classId"] = 2,
            ["gender"] = 1,
            ["avaRank"] = 7,
            ["raceId"] = 7,
            ["server"] = "NA Megaserver",
            ["alliance"] = 1,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077181565",
        },
        ["8796093077153837"] = 
        {
            ["level"] = 50,
            ["name"] = "Yang Yyds",
            ["rawName"] = "Yang Yyds^Mx",
            ["classId"] = 1,
            ["gender"] = 2,
            ["avaRank"] = 17,
            ["raceId"] = 1,
            ["server"] = "NA Megaserver",
            ["alliance"] = 1,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077153837",
        },
        ["8796093077280363"] = 
        {
            ["level"] = 50,
            ["name"] = "noobsmile",
            ["rawName"] = "noobsmile^Fx",
            ["classId"] = 117,
            ["gender"] = 1,
            ["avaRank"] = 4,
            ["id"] = "8796093077280363",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 4,
        },
        ["8796093079748457"] = 
        {
            ["level"] = 25,
            ["name"] = "Kaaskop",
            ["rawName"] = "Kaaskop^Fx",
            ["classId"] = 4,
            ["gender"] = 1,
            ["avaRank"] = 12,
            ["raceId"] = 1,
            ["server"] = "NA Megaserver",
            ["alliance"] = 3,
            ["account"] = "@Kankerkop",
            ["id"] = "8796093079748457",
        },
        ["8798292100191884"] = 
        {
            ["level"] = 1,
            ["name"] = "noobkiss",
            ["rawName"] = "noobkiss^Mx",
            ["classId"] = 1,
            ["gender"] = 2,
            ["avaRank"] = 2,
            ["raceId"] = 5,
            ["server"] = "EU Megaserver",
            ["alliance"] = 2,
            ["account"] = "@noobkiss",
            ["id"] = "8798292100191884",
        },
        ["8796093077181623"] = 
        {
            ["level"] = 50,
            ["name"] = "Aqi Yaa",
            ["rawName"] = "Aqi Yaa^Fx",
            ["classId"] = 4,
            ["gender"] = 1,
            ["avaRank"] = 17,
            ["raceId"] = 7,
            ["server"] = "NA Megaserver",
            ["alliance"] = 1,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077181623",
        },
        ["8796093077977317"] = 
        {
            ["level"] = 50,
            ["name"] = "Simmy Seek Snow",
            ["rawName"] = "Simmy Seek Snow^Fx",
            ["classId"] = 4,
            ["gender"] = 1,
            ["avaRank"] = 6,
            ["id"] = "8796093077977317",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 6,
        },
        ["8796093077354797"] = 
        {
            ["level"] = 50,
            ["name"] = "noobsmell",
            ["rawName"] = "noobsmell^Mx",
            ["classId"] = 3,
            ["gender"] = 2,
            ["avaRank"] = 13,
            ["id"] = "8796093077354797",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 9,
        },
        ["8796093080650625"] = 
        {
            ["level"] = 3,
            ["name"] = "Flawed Mangoes",
            ["rawName"] = "Flawed Mangoes^Mx",
            ["classId"] = 2,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["id"] = "8796093080650625",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 4,
        },
        ["8796093076445407"] = 
        {
            ["level"] = 50,
            ["name"] = "noobkiss",
            ["rawName"] = "noobkiss^Fx",
            ["classId"] = 1,
            ["gender"] = 1,
            ["avaRank"] = 14,
            ["id"] = "8796093076445407",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 5,
        },
        ["8796093077280469"] = 
        {
            ["level"] = 50,
            ["name"] = "noobxoxo",
            ["rawName"] = "noobxoxo^Fx",
            ["classId"] = 3,
            ["gender"] = 1,
            ["avaRank"] = 0,
            ["id"] = "8796093077280469",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 1,
        },
        ["8796093078606003"] = 
        {
            ["level"] = 50,
            ["name"] = "Kankerkop",
            ["rawName"] = "Kankerkop^Mx",
            ["classId"] = 1,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["raceId"] = 4,
            ["server"] = "NA Megaserver",
            ["alliance"] = 2,
            ["account"] = "@Kankerkop",
            ["id"] = "8796093078606003",
        },
        ["8796093077616617"] = 
        {
            ["level"] = 50,
            ["name"] = "shiaqi",
            ["rawName"] = "shiaqi^Mx",
            ["classId"] = 5,
            ["gender"] = 2,
            ["avaRank"] = 2,
            ["raceId"] = 5,
            ["server"] = "NA Megaserver",
            ["alliance"] = 2,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077616617",
        },
        ["8796093079602369"] = 
        {
            ["level"] = 50,
            ["name"] = "Zou Kimcheng",
            ["rawName"] = "Zou Kimcheng^Mx",
            ["classId"] = 1,
            ["gender"] = 2,
            ["avaRank"] = 44,
            ["id"] = "8796093079602369",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 10,
        },
        ["8796093080564143"] = 
        {
            ["level"] = 3,
            ["name"] = "Wasted Wasted",
            ["rawName"] = "Wasted Wasted^Mx",
            ["classId"] = 5,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["id"] = "8796093080564143",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 2,
        },
        ["8796093077165965"] = 
        {
            ["level"] = 50,
            ["name"] = "Junjunya",
            ["rawName"] = "Junjunya^Mx",
            ["classId"] = 117,
            ["gender"] = 2,
            ["avaRank"] = 8,
            ["raceId"] = 4,
            ["server"] = "NA Megaserver",
            ["alliance"] = 2,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077165965",
        },
        ["8796093077181587"] = 
        {
            ["level"] = 50,
            ["name"] = "a qi ya",
            ["rawName"] = "a qi ya^Mx",
            ["classId"] = 3,
            ["gender"] = 2,
            ["avaRank"] = 9,
            ["raceId"] = 9,
            ["server"] = "NA Megaserver",
            ["alliance"] = 2,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077181587",
        },
        ["8796093077280431"] = 
        {
            ["level"] = 50,
            ["name"] = "noobwink",
            ["rawName"] = "noobwink^Mx",
            ["classId"] = 5,
            ["gender"] = 2,
            ["avaRank"] = 2,
            ["id"] = "8796093077280431",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 2,
            ["raceId"] = 5,
        },
        ["8796093077130605"] = 
        {
            ["level"] = 50,
            ["name"] = "noobhugs",
            ["rawName"] = "noobhugs^Fx",
            ["classId"] = 2,
            ["gender"] = 1,
            ["avaRank"] = 21,
            ["id"] = "8796093077130605",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 7,
        },
        ["8796093078411849"] = 
        {
            ["level"] = 50,
            ["name"] = "Young Ming",
            ["rawName"] = "Young Ming^Mx",
            ["classId"] = 6,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["id"] = "8796093078411849",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 5,
        },
        ["8796093077976825"] = 
        {
            ["level"] = 50,
            ["name"] = "Sunken Feb",
            ["rawName"] = "Sunken Feb^Fx",
            ["classId"] = 5,
            ["gender"] = 1,
            ["avaRank"] = 0,
            ["id"] = "8796093077976825",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 8,
        },
        ["8796093077595053"] = 
        {
            ["level"] = 50,
            ["name"] = "aqi ya",
            ["rawName"] = "aqi ya^Mx",
            ["classId"] = 5,
            ["gender"] = 2,
            ["avaRank"] = 0,
            ["raceId"] = 4,
            ["server"] = "NA Megaserver",
            ["alliance"] = 2,
            ["account"] = "@YYDS1214",
            ["id"] = "8796093077595053",
        },
        ["8796093077286887"] = 
        {
            ["level"] = 50,
            ["name"] = "noobhappy",
            ["rawName"] = "noobhappy^Fx",
            ["classId"] = 4,
            ["gender"] = 1,
            ["avaRank"] = 18,
            ["id"] = "8796093077286887",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 1,
            ["raceId"] = 7,
        },
        ["8796093077977575"] = 
        {
            ["level"] = 50,
            ["name"] = "Killswitch Memories",
            ["rawName"] = "Killswitch Memories^Mx",
            ["classId"] = 2,
            ["gender"] = 2,
            ["avaRank"] = 4,
            ["id"] = "8796093077977575",
            ["server"] = "NA Megaserver",
            ["account"] = "@noobkiss",
            ["alliance"] = 3,
            ["raceId"] = 5,
        },
    },
}
