NO_THANK_YOU_VARS =
{
    ["Default"] = 
    {
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["dontAcceptWritQuest"] = false,
                ["noCameraSpin"] = false,
                ["emptyInteractions"] = false,
                ["largeGroupDialog"] = false,
                ["hideTamriel"] = false,
                ["dontReadBooks"] = false,
                ["dontShowSkillProgression"] = 0,
                ["raidGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["dontShowLoreDiscoveries"] = 0,
                ["noCameraSpinStats"] = false,
                ["luaError"] = 1,
                ["fenceDialog"] = false,
                ["unownedHouses"] = 0,
                ["boss"] = false,
                ["guildAlerts"] = 0,
                ["raid"] = 0,
                ["emptyMail"] = true,
                ["craftBag"] = false,
                ["alertTextExpiryDelay"] = 3,
                ["groupZone"] = 1,
                ["hideTamrielWayhsrines"] = 0,
                ["motd"] = 0,
                ["endless"] = true,
                ["enlightened"] = false,
                ["guildInvites"] = 0,
                ["autoLootItems"] = false,
                ["guildAlertsGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["hideTamrielDungeons"] = 0,
                ["chatForTradingHouse"] = false,
                ["notificationSound"] = false,
                ["marketAnnouncement"] = false,
                ["noCameraSpinInv"] = false,
                ["ultimateSound"] = 0,
                ["friends"] = false,
                ["noBindAlert"] = false,
                ["motdGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["repair"] = false,
                ["nonstopHarvest"] = false,
                ["disableChatAutoComplete"] = false,
                ["guildLeave"] = 
                {
                },
                ["raidToChat"] = true,
                ["disbandDialog"] = false,
                ["ava"] = 1,
                ["ownedHouses"] = 0,
                ["noUniversalStones"] = false,
                ["screenshot"] = false,
                ["noReportOnItems"] = false,
                ["noPortOnLeader"] = 0,
                ["guildApps"] = false,
                ["version"] = 2,
                ["noGuildLeave"] = 0,
                ["improveDialog"] = false,
                ["craftingResults"] = false,
                ["crownCrate"] = false,
            },
        },
        ["@Kankerkop"] = 
        {
            ["$AccountWide"] = 
            {
                ["dontAcceptWritQuest"] = false,
                ["noCameraSpin"] = false,
                ["emptyInteractions"] = false,
                ["largeGroupDialog"] = false,
                ["hideTamriel"] = false,
                ["dontReadBooks"] = false,
                ["dontShowSkillProgression"] = 0,
                ["raidGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["dontShowLoreDiscoveries"] = 0,
                ["noCameraSpinStats"] = false,
                ["luaError"] = 1,
                ["fenceDialog"] = false,
                ["unownedHouses"] = 0,
                ["boss"] = false,
                ["guildAlerts"] = 0,
                ["raid"] = 0,
                ["emptyMail"] = true,
                ["craftBag"] = false,
                ["alertTextExpiryDelay"] = 3,
                ["groupZone"] = 1,
                ["hideTamrielWayhsrines"] = 0,
                ["motd"] = 0,
                ["endless"] = true,
                ["enlightened"] = false,
                ["guildInvites"] = 0,
                ["autoLootItems"] = false,
                ["guildAlertsGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["hideTamrielDungeons"] = 0,
                ["chatForTradingHouse"] = false,
                ["notificationSound"] = false,
                ["marketAnnouncement"] = false,
                ["noCameraSpinInv"] = false,
                ["ultimateSound"] = 0,
                ["friends"] = false,
                ["noBindAlert"] = false,
                ["motdGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["repair"] = false,
                ["nonstopHarvest"] = false,
                ["disableChatAutoComplete"] = false,
                ["guildLeave"] = 
                {
                },
                ["raidToChat"] = true,
                ["disbandDialog"] = false,
                ["ava"] = 1,
                ["ownedHouses"] = 0,
                ["noUniversalStones"] = false,
                ["screenshot"] = false,
                ["noReportOnItems"] = false,
                ["noPortOnLeader"] = 0,
                ["guildApps"] = false,
                ["version"] = 2,
                ["noGuildLeave"] = 0,
                ["improveDialog"] = false,
                ["craftingResults"] = false,
                ["crownCrate"] = false,
            },
        },
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["dontAcceptWritQuest"] = false,
                ["noCameraSpin"] = false,
                ["emptyInteractions"] = false,
                ["largeGroupDialog"] = false,
                ["hideTamriel"] = false,
                ["dontReadBooks"] = false,
                ["dontShowSkillProgression"] = 0,
                ["raidGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["dontShowLoreDiscoveries"] = 0,
                ["noCameraSpinStats"] = false,
                ["luaError"] = 2,
                ["fenceDialog"] = false,
                ["unownedHouses"] = 0,
                ["boss"] = false,
                ["guildAlerts"] = 0,
                ["raid"] = 0,
                ["emptyMail"] = true,
                ["craftBag"] = false,
                ["alertTextExpiryDelay"] = 3,
                ["groupZone"] = 0,
                ["hideTamrielWayhsrines"] = 0,
                ["motd"] = 0,
                ["endless"] = true,
                ["enlightened"] = false,
                ["guildInvites"] = 0,
                ["autoLootItems"] = false,
                ["guildAlertsGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["hideTamrielDungeons"] = 0,
                ["chatForTradingHouse"] = false,
                ["notificationSound"] = false,
                ["marketAnnouncement"] = false,
                ["noCameraSpinInv"] = false,
                ["ultimateSound"] = 0,
                ["friends"] = false,
                ["noBindAlert"] = false,
                ["motdGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["repair"] = false,
                ["nonstopHarvest"] = false,
                ["disableChatAutoComplete"] = false,
                ["guildLeave"] = 
                {
                },
                ["raidToChat"] = true,
                ["disbandDialog"] = false,
                ["ava"] = 0,
                ["ownedHouses"] = 0,
                ["noUniversalStones"] = false,
                ["screenshot"] = false,
                ["noReportOnItems"] = false,
                ["noPortOnLeader"] = 0,
                ["guildApps"] = false,
                ["version"] = 2,
                ["noGuildLeave"] = 0,
                ["improveDialog"] = false,
                ["craftingResults"] = false,
                ["crownCrate"] = false,
            },
        },
        ["@YYDS1214"] = 
        {
            ["$AccountWide"] = 
            {
                ["dontAcceptWritQuest"] = false,
                ["noCameraSpin"] = false,
                ["emptyInteractions"] = false,
                ["largeGroupDialog"] = false,
                ["hideTamriel"] = false,
                ["dontReadBooks"] = false,
                ["dontShowSkillProgression"] = 0,
                ["raidGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["dontShowLoreDiscoveries"] = 0,
                ["noCameraSpinStats"] = false,
                ["luaError"] = 1,
                ["fenceDialog"] = false,
                ["unownedHouses"] = 0,
                ["boss"] = false,
                ["guildAlerts"] = 0,
                ["raid"] = 0,
                ["emptyMail"] = true,
                ["craftBag"] = false,
                ["alertTextExpiryDelay"] = 3,
                ["groupZone"] = 1,
                ["hideTamrielWayhsrines"] = 0,
                ["motd"] = 0,
                ["endless"] = true,
                ["enlightened"] = false,
                ["guildInvites"] = 0,
                ["autoLootItems"] = false,
                ["guildAlertsGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["hideTamrielDungeons"] = 0,
                ["chatForTradingHouse"] = false,
                ["notificationSound"] = false,
                ["marketAnnouncement"] = false,
                ["noCameraSpinInv"] = false,
                ["ultimateSound"] = 0,
                ["friends"] = false,
                ["noBindAlert"] = false,
                ["motdGuilds"] = 
                {
                    [1] = true,
                    [2] = true,
                    [3] = true,
                    [4] = true,
                    [5] = true,
                },
                ["repair"] = false,
                ["nonstopHarvest"] = false,
                ["disableChatAutoComplete"] = false,
                ["guildLeave"] = 
                {
                },
                ["raidToChat"] = true,
                ["disbandDialog"] = false,
                ["ava"] = 1,
                ["ownedHouses"] = 0,
                ["noUniversalStones"] = false,
                ["screenshot"] = false,
                ["noReportOnItems"] = false,
                ["noPortOnLeader"] = 0,
                ["guildApps"] = false,
                ["version"] = 2,
                ["noGuildLeave"] = 0,
                ["improveDialog"] = false,
                ["craftingResults"] = false,
                ["crownCrate"] = false,
            },
        },
    },
}
