ReminderzSavedVars =
{
    ["NA Megaserver"] = 
    {
        ["@noobkiss"] = 
        {
            ["8796093079602369"] = 
            {
                ["apRemind"] = false,
                ["foodRemindPVPOnly"] = false,
                ["$LastCharacterName"] = "Zou Kimcheng",
                ["xpFirstReminder"] = 3,
                ["telvarAutoDeposit"] = true,
                ["xpRemindInterval"] = 1,
                ["foodRemindInterval"] = 1,
                ["bagRemind"] = 1,
                ["vampRemindInterval"] = 1,
                ["foodDontRemindInHouses"] = false,
                ["vampDontRemindInHouses"] = false,
                ["foodOnlyRemindInDungeons"] = false,
                ["xpDontRemindInHouses"] = false,
                ["telvarReserveAmount"] = 0,
                ["suppressLoaded"] = true,
                ["checkGear"] = false,
                ["vampStage"] = 0,
                ["foodRemindColor"] = "ffff00",
                ["xpRemindPVPOnly"] = false,
                ["trackAchievements"] = true,
                ["leadsRemindColor"] = "f1c232",
                ["foodRemind"] = true,
                ["whisperOfflineWarning"] = true,
                ["vampRemindPVPOnly"] = false,
                ["foodFirstReminder"] = 3,
                ["apRemindInterval"] = 1,
                ["leadsDaysUntilExpire"] = 1,
                ["apFirstReminder"] = 3,
                ["xpRemindColor"] = "22addc",
                ["vampFirstReminder"] = 3,
                ["apRemindPVPOnly"] = false,
                ["xpRemind"] = false,
                ["autoDailyReward"] = true,
                ["apRemindColor"] = "ff8740",
                ["version"] = 2,
                ["apDontRemindInHouses"] = false,
                ["accountWide"] = false,
                ["telvarRemind"] = 0,
                ["remindersToChat"] = true,
                ["vampRemindColor"] = "ff1919",
            },
            ["$AccountWide"] = 
            {
                ["apRemind"] = false,
                ["foodRemindPVPOnly"] = false,
                ["whisperOfflineWarning"] = true,
                ["xpFirstReminder"] = 3,
                ["telvarAutoDeposit"] = true,
                ["xpRemindInterval"] = 1,
                ["foodRemindInterval"] = 1,
                ["bagRemind"] = 1,
                ["vampRemindInterval"] = 1,
                ["foodDontRemindInHouses"] = false,
                ["vampDontRemindInHouses"] = false,
                ["foodOnlyRemindInDungeons"] = false,
                ["xpDontRemindInHouses"] = false,
                ["telvarReserveAmount"] = 0,
                ["suppressLoaded"] = true,
                ["checkGear"] = false,
                ["vampStage"] = 0,
                ["foodRemindColor"] = "ffff00",
                ["xpRemindPVPOnly"] = false,
                ["trackAchievements"] = false,
                ["leadsRemindColor"] = "f1c232",
                ["foodRemind"] = true,
                ["vampRemindPVPOnly"] = false,
                ["apFirstReminder"] = 3,
                ["apRemindInterval"] = 1,
                ["foodFirstReminder"] = 3,
                ["leadsDaysUntilExpire"] = 1,
                ["xpRemindColor"] = "22addc",
                ["vampFirstReminder"] = 3,
                ["apRemindPVPOnly"] = false,
                ["xpRemind"] = false,
                ["autoDailyReward"] = true,
                ["apRemindColor"] = "ff8740",
                ["version"] = 2,
                ["apDontRemindInHouses"] = false,
                ["accountWide"] = true,
                ["telvarRemind"] = 0,
                ["remindersToChat"] = true,
                ["vampRemindColor"] = "ff1919",
            },
        },
    },
}
