ShowTTCPriceVars =
{
    ["Default"] = 
    {
        ["@YYDS1214"] = 
        {
            ["$AccountWide"] = 
            {
                ["NA Megaserver"] = 
                {
                    ["RoundNumbers"] = true,
                    ["HighlightReq"] = false,
                    ["RiskyDealsListingsCount"] = 10,
                    ["ProfitFilterSliderMin"] = "0",
                    ["IgnoreBoundItems"] = true,
                    ["version"] = 3,
                    ["DesiredValue"] = 5000,
                    ["EnableProfitFilter"] = true,
                    ["RequiredValue"] = 25,
                    ["EnableAwesomeGuildStoreIntegration"] = true,
                    ["Enabled"] = true,
                    ["ListingPreferredPrice"] = "Sales Average",
                    ["PriceToShow"] = "Stack and Unit",
                    ["EnableInGuildStore"] = true,
                    ["EnableDealFilter"] = true,
                    ["FallbackPriceGS"] = "None",
                    ["FallbackPrice"] = "Average",
                    ["IgnoreBelowVendor"] = true,
                    ["EnableToggleButton"] = false,
                    ["GuildStoreInfoToShow"] = "Profit",
                    ["IgnoreTrash"] = true,
                    ["HighlightRiskyDeals"] = true,
                    ["PreferredPrice"] = "Sales Average",
                    ["MinimumReq"] = false,
                },
            },
        },
        ["@noobkiss"] = 
        {
            ["$AccountWide"] = 
            {
                ["NA Megaserver"] = 
                {
                    ["RoundNumbers"] = true,
                    ["HighlightReq"] = false,
                    ["RiskyDealsListingsCount"] = 10,
                    ["ProfitFilterSliderMin"] = "0",
                    ["IgnoreBoundItems"] = true,
                    ["version"] = 3,
                    ["DesiredValue"] = 5000,
                    ["EnableProfitFilter"] = true,
                    ["RequiredValue"] = 25,
                    ["EnableAwesomeGuildStoreIntegration"] = true,
                    ["Enabled"] = true,
                    ["ListingPreferredPrice"] = "Sales Average",
                    ["PriceToShow"] = "Stack and Unit",
                    ["EnableInGuildStore"] = false,
                    ["EnableDealFilter"] = true,
                    ["FallbackPriceGS"] = "None",
                    ["FallbackPrice"] = "Average",
                    ["IgnoreBelowVendor"] = true,
                    ["EnableToggleButton"] = false,
                    ["GuildStoreInfoToShow"] = "Profit",
                    ["IgnoreTrash"] = true,
                    ["HighlightRiskyDeals"] = true,
                    ["PreferredPrice"] = "Sales Average",
                    ["MinimumReq"] = false,
                },
                ["EU Megaserver"] = 
                {
                    ["RoundNumbers"] = true,
                    ["HighlightReq"] = false,
                    ["RiskyDealsListingsCount"] = 10,
                    ["ProfitFilterSliderMin"] = "0",
                    ["IgnoreBoundItems"] = true,
                    ["version"] = 3,
                    ["DesiredValue"] = 5000,
                    ["EnableProfitFilter"] = true,
                    ["RequiredValue"] = 25,
                    ["EnableAwesomeGuildStoreIntegration"] = true,
                    ["Enabled"] = true,
                    ["ListingPreferredPrice"] = "Sales Average",
                    ["PriceToShow"] = "Stack and Unit",
                    ["EnableInGuildStore"] = true,
                    ["EnableDealFilter"] = true,
                    ["FallbackPriceGS"] = "None",
                    ["FallbackPrice"] = "Average",
                    ["IgnoreBelowVendor"] = true,
                    ["EnableToggleButton"] = false,
                    ["GuildStoreInfoToShow"] = "Profit",
                    ["IgnoreTrash"] = true,
                    ["HighlightRiskyDeals"] = true,
                    ["PreferredPrice"] = "Sales Average",
                    ["MinimumReq"] = false,
                },
            },
        },
        ["@Kankerkop"] = 
        {
            ["$AccountWide"] = 
            {
                ["NA Megaserver"] = 
                {
                    ["RoundNumbers"] = true,
                    ["HighlightReq"] = false,
                    ["RiskyDealsListingsCount"] = 10,
                    ["ProfitFilterSliderMin"] = "0",
                    ["IgnoreBoundItems"] = true,
                    ["version"] = 3,
                    ["DesiredValue"] = 5000,
                    ["EnableProfitFilter"] = true,
                    ["RequiredValue"] = 25,
                    ["EnableAwesomeGuildStoreIntegration"] = true,
                    ["Enabled"] = true,
                    ["ListingPreferredPrice"] = "Sales Average",
                    ["PriceToShow"] = "Stack and Unit",
                    ["EnableInGuildStore"] = true,
                    ["EnableDealFilter"] = true,
                    ["FallbackPriceGS"] = "None",
                    ["FallbackPrice"] = "Average",
                    ["IgnoreBelowVendor"] = true,
                    ["EnableToggleButton"] = false,
                    ["GuildStoreInfoToShow"] = "Profit",
                    ["IgnoreTrash"] = true,
                    ["HighlightRiskyDeals"] = true,
                    ["PreferredPrice"] = "Suggested",
                    ["MinimumReq"] = false,
                },
            },
        },
        ["@Jonzouio"] = 
        {
            ["$AccountWide"] = 
            {
                ["NA Megaserver"] = 
                {
                    ["RoundNumbers"] = true,
                    ["HighlightReq"] = false,
                    ["RiskyDealsListingsCount"] = 10,
                    ["IgnoreTrash"] = true,
                    ["IgnoreBoundItems"] = true,
                    ["version"] = 3,
                    ["DesiredValue"] = 5000,
                    ["EnableProfitFilter"] = true,
                    ["RequiredValue"] = 25,
                    ["EnableAwesomeGuildStoreIntegration"] = true,
                    ["Enabled"] = true,
                    ["PriceToShow"] = "Stack and Unit",
                    ["EnableInGuildStore"] = true,
                    ["IgnoreBelowVendor"] = true,
                    ["EnableToggleButton"] = false,
                    ["GuildStoreInfoToShow"] = "Profit",
                    ["EnableDealFilter"] = true,
                    ["HighlightRiskyDeals"] = true,
                    ["PreferredPrice"] = "Suggested",
                    ["MinimumReq"] = false,
                },
            },
        },
    },
}
